[project]
name = "pfw-2526-3ia1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==5.2.*",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
]
